 
import Footer from '@/components/global/footer';
import Header from '@/components/global/header' 
import Head from 'next/head'

const PrivacyPolicy = () => {
  return (
    <>
     <Head>
        <title>Privacy Policy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/fav.png" />
    </Head>
    <Header />
    <section className="bg-gray-100 py-12">
        <div className="container mx-auto px-4">
            <div className="max-w-3xl mx-auto">
                <h2 className="text-3xl font-bold text-gray-800 mb-6">Privacy Policy</h2>
                <p className="text-sm text-gray-600 mb-8">Last Updated on April 11, 2024</p>
            
                <div className="text-gray-700 mt-8">
                    <h3 className="text-xl font-semibold mb-4">Consent for Collection, Use and Disclosure:</h3>
                    <p>Your use of this site and/or your registration for products and services here constitute your consent to the terms of this Privacy Policy. If you do not agree to the terms of this Privacy Policy, please do not use this website.</p>
                </div>

                <div className="text-gray-700 mt-8">
                    <h3 className="text-xl font-semibold mb-4">Accountability:</h3>
                    <p>We collect, at the time of your registration and your sign-on to its web site, certain “personal information” (information that personally identifies you) including but not limited to your name, email address, and information about IP address. We take responsibility for your personal information to ensure compliance with the principles in this Privacy Policy.</p>
                </div>

                <div className="text-gray-700 mt-8">
                    <h3 className="text-xl font-semibold mb-4">Purposes for Collecting Personal Information:</h3>
                    <p>We collect and use personal information for the following Identified Purposes:<br/>
                    - To understand customer needs regarding our services.<br/>
                    - To develop and provide our web site and our products and services for our customers.<br/>
                    - To fulfill your requests for products, services or information.<br/>
                    - To communicate with customers and site visitors, when necessary, and to inform customers of upgrades, as well as of other products and services available.<br/>
                    - To allow customers to access limited-entry areas of our site.<br/>
                    - To personalize some of our services and products for you and to deliver targeted advertisements and offers.<br/>
                    - To protect the services, products or rights of – including but not limited to the security or integrity of our website.<br/>
                    - To identify and resolve technical problems concerning our site, products, and services.<br/>
                    - We also use personal information in an aggregate form (i.e., not individually attributable to you) for its business analysis, operational, marketing and other promotional purposes.</p>
                </div>

                <div className="text-gray-700 mt-8">
                    <h3 className="text-xl font-semibold mb-4">Limiting the Collection of Personal Information:</h3>
                    <p>We limit our collection of personal information to only that information which is necessary for the Identified Purposes. We do not direct our site to, nor does it knowingly collect any personal information from children under the age of thirteen.</p>
                    <p>When you visit our website, a cookie may be placed on your computer or the cookie may be read if you have visited our web site previously. We use cookies to allow us to determine which products and services you have already purchased/interested in, so that we do not provide redundant information to you, If you choose to not have your browser accept cookies from our web site, you may not be able to view all the text on the screens, or to experience a personalized visit, or to subscribe to certain service and product offerings on our website.</p>
                </div>

                <div className="text-gray-700 mt-8">
                    <h3 className="text-xl font-semibold mb-4">Disclosure, Processing, and Retention:</h3>
                    <p>We do not sell, rent or disclose your personal information to anyone else.</p>
                </div>

                <div className="container mx-auto px-4">
                    <div className="max-w-3xl mx-auto">
                        <div className="text-gray-700 mt-8">
                            <h3 className="text-xl font-semibold mb-4">Security Safeguards:</h3>
                            <p>We will use reasonable efforts to protect customers.</p>
                            <div className="prohibition-text mt-4">
                                <p className="text-red-600 font-semibold">COPYING, DISTRIBUTING, UNAUTHORIZED ACCESS</p>
                                <p className="text-red-600 font-semibold">OF ANY CONTENT INCLUDING TEXT, IMAGES, STRATEGY, MAPS OR ANY OTHER ELEMENT PUBLISHED ON THIS SITE IS STRICTLY PROHIBITED.</p>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </section>

    <Footer  />
    </>
  );
};

export default PrivacyPolicy;
