import React from 'react';
import Footer from '@/components/global/footer';
import Header from '@/components/global/header';
import Head from 'next/head';

const TermsAndConditions = () => {
  return (
    <>
      <Head>
        <title>Terms & Conditions</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/image.png" />
      </Head>
      <Header />
      <section className="bg-gray-100 py-12">
        <div className="container mx-auto px-4">
          <div className="max-w-3xl mx-auto">
            <h2 className="text-3xl text-left font-bold text-gray-800 mb-6">Terms & Conditions</h2>
            <p className="text-sm text-left text-gray-600 mb-8">Last Updated on April 11, 2024</p>

            <div className="mb-8">
              <h3 className="text-xl text-left font-semibold text-gray-800 mb-4">Use of Our Website</h3>
              <p className="text-gray-700 mb-2">You are permitted to use this site for your own purposes to print, download, and share material provided you do not modify any content without our explicit consent. Material on this website may not be republished online or offline without our permission. The copyright and all intellectual property rights of the material on this site are owned by Beamen Tech LLC and may not be reproduced without our prior consent.</p>
            </div>

            <div className="mb-8">
              <h3 className="text-xl text-left font-semibold text-gray-800 mb-4">Visitor Conduct</h3>
              <p className="text-gray-700 mb-2">With the exception of personal information (the use of which is covered under our Privacy Policy), any material you send or post to this write shall be considered non-proprietary and not confidential. Unless you advise to the contrary, we remain free to copy, disclose, distribute, incorporate and otherwise use such material for any and all purposes.</p>
              <p className="text-gray-700 mb-2">When using the site, please do not post or send any material for which you have not obtained all necessary consents or that which is discriminatory, obscene, pornographic, defamatory, liable to incite racial hatred, in breach of confidentiality or privacy to or from this site, which may cause annoyance or inconvenience to others, which encourages or constitutes conduct that would be deemed a criminal offense, give rise to a civil liability, or otherwise is contrary to the law of the United States of America.</p>
            </div>

            <div className="mb-8">
              <h3 className="text-xl text-left font-semibold text-gray-800 mb-4">Site Activity</h3>
              <p className="text-gray-700 mb-2">We take the utmost care to ensure that this site is available 24/7, 365 days per year. However, websites do sometimes encounter downtime due to server or technical issues. We are not liable if this website is unavailable at any time.</p>
            </div>

            <div className="mb-8">
              <h3 className="text-xl text-left font-semibold text-gray-800 mb-4">Links to and from other Websites</h3>
              <p className="text-gray-700 mb-2">In order to provide additional information or services, Beamen Tech LLC may include links to external websites. Clicking on such a link will navigate you away from the Digital Marketing Agencies site. The inclusion of links does not necessarily imply a recommendation, nor does it in any way endorse the views expressed within them. Other site’s Terms and Conditions may differ from our own. When clicking off the Beamen Tech LLC site, we strongly encourage you to visit the other site’s Terms and Conditions to ensure it meets the standards of your own personal preferences.</p>
            </div>

            <div className="mb-8">
              <h3 className="text-xl text-left font-semibold text-gray-800 mb-4">Exclusion of Liability</h3>
              <p className="text-gray-700 mb-2">In no event will Beamen Tech LLC be held liable for any loss or damage of information including but not limited to indirect or consequential loss or damage, loss or damage of data, or profits arising out of or in connection with the use of this website. Beamen Tech LLC may not be held liable or responsible in any way for loss or damage that may result to you or a third party as a result of your use of our website.</p>
              <p className="text-gray-700 mb-2">We take the utmost measures to ensure that the information provided on this site is correct, however; we do not make any guarantees regarding that information. This exclusion shall include servicing or repair costs and, without limitation, any other direct, indirect or consequential loss.</p>
            </div>

            <div className="mb-8">
              <h3 className="text-xl text-left font-semibold text-gray-800 mb-4">Governing Law</h3>
              <p className="text-gray-700 mb-2">These legal Terms and Conditions apply for all issues regarding this website shall be governed by the laws of the United States of America and in the state of New Mexico or the appropriate defending country.</p>
            </div>

            <div className="mb-8">
              <h3 className="text-xl text-left font-semibold text-gray-800 mb-4">Contacting us</h3>
              <p className="text-gray-700 mb-2">If you have any questions regarding our Terms and Conditions or your dealings with scribe-ace.vercel.app, please contact through our Contact Form, or with the following information:</p>
              <p className="text-gray-700 mb-2">Beamen Tech LLC</p>
              <p className="text-gray-700 mb-2">564 4th Ave, San Bruno, CA 94066</p>
              <p className="text-gray-700 mb-2"> <a href="tel:8554386037">+1 (855) 438-6037</a></p>
              <p className="text-gray-700 mb-2"><a href="mailto:admin@cabledeal.live">admin@cabledeal.live</a></p>
            </div>

          </div>
        </div>
      </section>
      <Footer />
    </>
  );
};

export default TermsAndConditions;
